"""
sample_data.py — Generate a realistic TMDB-shaped demo dataset so the app
works out of the box without the full Kaggle CSV files.
"""

import numpy as np
import pandas as pd

MOVIES = [
    # (title, genres, keywords, cast, director, overview, year, rating, votes, runtime)
    ("The Dark Knight",
     "[{'id':28,'name':'Action'},{'id':80,'name':'Crime'},{'id':18,'name':'Drama'}]",
     "[{'id':849,'name':'joker'},{'id':9748,'name':'vigilante'},{'id':1562,'name':'gotham city'}]",
     "[{'name':'Christian Bale'},{'name':'Heath Ledger'},{'name':'Aaron Eckhart'}]",
     "[{'name':'Christopher Nolan','job':'Director'}]",
     "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets of Gotham.",
     2008, 8.5, 22000, 152),

    ("Inception",
     "[{'id':28,'name':'Action'},{'id':878,'name':'Science Fiction'},{'id':12,'name':'Adventure'}]",
     "[{'id':1562,'name':'dream'},{'id':849,'name':'subconscious'},{'id':9748,'name':'heist'}]",
     "[{'name':'Leonardo DiCaprio'},{'name':'Joseph Gordon-Levitt'},{'name':'Ellen Page'}]",
     "[{'name':'Christopher Nolan','job':'Director'}]",
     "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
     2010, 8.8, 33000, 148),

    ("Interstellar",
     "[{'id':12,'name':'Adventure'},{'id':18,'name':'Drama'},{'id':878,'name':'Science Fiction'}]",
     "[{'id':1562,'name':'space'},{'id':849,'name':'black hole'},{'id':9748,'name':'time travel'}]",
     "[{'name':'Matthew McConaughey'},{'name':'Anne Hathaway'},{'name':'Jessica Chastain'}]",
     "[{'name':'Christopher Nolan','job':'Director'}]",
     "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
     2014, 8.6, 29000, 169),

    ("The Matrix",
     "[{'id':28,'name':'Action'},{'id':878,'name':'Science Fiction'}]",
     "[{'id':1562,'name':'virtual reality'},{'id':849,'name':'hacker'},{'id':9748,'name':'dystopia'}]",
     "[{'name':'Keanu Reeves'},{'name':'Laurence Fishburne'},{'name':'Carrie-Anne Moss'}]",
     "[{'name':'Lana Wachowski','job':'Director'}]",
     "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
     1999, 8.7, 19000, 136),

    ("Avatar",
     "[{'id':28,'name':'Action'},{'id':12,'name':'Adventure'},{'id':878,'name':'Science Fiction'}]",
     "[{'id':1562,'name':'alien'},{'id':849,'name':'military'},{'id':9748,'name':'nature'}]",
     "[{'name':'Sam Worthington'},{'name':'Zoe Saldana'},{'name':'Sigourney Weaver'}]",
     "[{'name':'James Cameron','job':'Director'}]",
     "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
     2009, 7.9, 25000, 162),

    ("Avengers: Endgame",
     "[{'id':28,'name':'Action'},{'id':12,'name':'Adventure'},{'id':878,'name':'Science Fiction'}]",
     "[{'id':1562,'name':'superhero'},{'id':849,'name':'time travel'},{'id':9748,'name':'marvel'}]",
     "[{'name':'Robert Downey Jr.'},{'name':'Chris Evans'},{'name':'Scarlett Johansson'}]",
     "[{'name':'Anthony Russo','job':'Director'}]",
     "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers must assemble once more.",
     2019, 8.4, 35000, 181),

    ("The Avengers",
     "[{'id':28,'name':'Action'},{'id':12,'name':'Adventure'},{'id':878,'name':'Science Fiction'}]",
     "[{'id':1562,'name':'superhero'},{'id':849,'name':'shield'},{'id':9748,'name':'marvel'}]",
     "[{'name':'Robert Downey Jr.'},{'name':'Chris Hemsworth'},{'name':'Mark Ruffalo'}]",
     "[{'name':'Joss Whedon','job':'Director'}]",
     "Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.",
     2012, 8.1, 28000, 143),

    ("Iron Man",
     "[{'id':28,'name':'Action'},{'id':12,'name':'Adventure'},{'id':878,'name':'Science Fiction'}]",
     "[{'id':1562,'name':'superhero'},{'id':849,'name':'billionaire'},{'id':9748,'name':'marvel'}]",
     "[{'name':'Robert Downey Jr.'},{'name':'Gwyneth Paltrow'},{'name':'Jeff Bridges'}]",
     "[{'name':'Jon Favreau','job':'Director'}]",
     "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.",
     2008, 7.9, 21000, 126),

    ("Pulp Fiction",
     "[{'id':80,'name':'Crime'},{'id':53,'name':'Thriller'}]",
     "[{'id':1562,'name':'nonlinear'},{'id':849,'name':'violence'},{'id':9748,'name':'los angeles'}]",
     "[{'name':'John Travolta'},{'name':'Uma Thurman'},{'name':'Samuel L. Jackson'}]",
     "[{'name':'Quentin Tarantino','job':'Director'}]",
     "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
     1994, 8.9, 23000, 154),

    ("The Godfather",
     "[{'id':18,'name':'Drama'},{'id':80,'name':'Crime'}]",
     "[{'id':1562,'name':'mafia'},{'id':849,'name':'family'},{'id':9748,'name':'power'}]",
     "[{'name':'Marlon Brando'},{'name':'Al Pacino'},{'name':'James Caan'}]",
     "[{'name':'Francis Ford Coppola','job':'Director'}]",
     "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
     1972, 9.2, 18000, 175),

    ("Forrest Gump",
     "[{'id':35,'name':'Comedy'},{'id':18,'name':'Drama'},{'id':10749,'name':'Romance'}]",
     "[{'id':1562,'name':'life'},{'id':849,'name':'history'},{'id':9748,'name':'destiny'}]",
     "[{'name':'Tom Hanks'},{'name':'Robin Wright'},{'name':'Gary Sinise'}]",
     "[{'name':'Robert Zemeckis','job':'Director'}]",
     "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate and other historical events unfold from the perspective of an Alabama man with an IQ of 75.",
     1994, 8.8, 25000, 142),

    ("The Lion King",
     "[{'id':16,'name':'Animation'},{'id':12,'name':'Adventure'},{'id':18,'name':'Drama'}]",
     "[{'id':1562,'name':'africa'},{'id':849,'name':'lion'},{'id':9748,'name':'kingdom'}]",
     "[{'name':'Matthew Broderick'},{'name':'James Earl Jones'},{'name':'Jeremy Irons'}]",
     "[{'name':'Roger Allers','job':'Director'}]",
     "Lion cub and future king Simba searches for his identity. His eagerness to please others and his own father's  shadow proves to be a challenge.",
     1994, 8.5, 16000, 88),

    ("Toy Story",
     "[{'id':16,'name':'Animation'},{'id':12,'name':'Adventure'},{'id':35,'name':'Comedy'}]",
     "[{'id':1562,'name':'toys'},{'id':849,'name':'friendship'},{'id':9748,'name':'adventure'}]",
     "[{'name':'Tom Hanks'},{'name':'Tim Allen'},{'name':'Joan Cusack'}]",
     "[{'name':'John Lasseter','job':'Director'}]",
     "A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy's room.",
     1995, 8.3, 14000, 81),

    ("The Silence of the Lambs",
     "[{'id':80,'name':'Crime'},{'id':18,'name':'Drama'},{'id':53,'name':'Thriller'}]",
     "[{'id':1562,'name':'fbi'},{'id':849,'name':'serial killer'},{'id':9748,'name':'psychology'}]",
     "[{'name':'Jodie Foster'},{'name':'Anthony Hopkins'},{'name':'Scott Glenn'}]",
     "[{'name':'Jonathan Demme','job':'Director'}]",
     "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.",
     1991, 8.6, 16000, 118),

    ("Schindler's List",
     "[{'id':18,'name':'Drama'},{'id':36,'name':'History'},{'id':10752,'name':'War'}]",
     "[{'id':1562,'name':'holocaust'},{'id':849,'name':'world war ii'},{'id':9748,'name':'germany'}]",
     "[{'name':'Liam Neeson'},{'name':'Ralph Fiennes'},{'name':'Ben Kingsley'}]",
     "[{'name':'Steven Spielberg','job':'Director'}]",
     "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
     1993, 9.0, 15000, 195),

    ("Fight Club",
     "[{'id':18,'name':'Drama'},{'id':53,'name':'Thriller'}]",
     "[{'id':1562,'name':'identity'},{'id':849,'name':'underground'},{'id':9748,'name':'anarchy'}]",
     "[{'name':'Brad Pitt'},{'name':'Edward Norton'},{'name':'Helena Bonham Carter'}]",
     "[{'name':'David Fincher','job':'Director'}]",
     "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",
     1999, 8.8, 24000, 139),

    ("Goodfellas",
     "[{'id':18,'name':'Drama'},{'id':80,'name':'Crime'}]",
     "[{'id':1562,'name':'mafia'},{'id':849,'name':'gangster'},{'id':9748,'name':'new york'}]",
     "[{'name':'Ray Liotta'},{'name':'Robert De Niro'},{'name':'Joe Pesci'}]",
     "[{'name':'Martin Scorsese','job':'Director'}]",
     "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito.",
     1990, 8.7, 17000, 146),

    ("The Shawshank Redemption",
     "[{'id':18,'name':'Drama'},{'id':80,'name':'Crime'}]",
     "[{'id':1562,'name':'prison'},{'id':849,'name':'hope'},{'id':9748,'name':'friendship'}]",
     "[{'name':'Tim Robbins'},{'name':'Morgan Freeman'},{'name':'Bob Gunton'}]",
     "[{'name':'Frank Darabont','job':'Director'}]",
     "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
     1994, 9.3, 26000, 142),

    ("Gladiator",
     "[{'id':28,'name':'Action'},{'id':12,'name':'Adventure'},{'id':18,'name':'Drama'}]",
     "[{'id':1562,'name':'rome'},{'id':849,'name':'revenge'},{'id':9748,'name':'arena'}]",
     "[{'name':'Russell Crowe'},{'name':'Joaquin Phoenix'},{'name':'Connie Nielsen'}]",
     "[{'name':'Ridley Scott','job':'Director'}]",
     "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
     2000, 8.5, 18000, 155),

    ("Titanic",
     "[{'id':18,'name':'Drama'},{'id':10749,'name':'Romance'},{'id':12,'name':'Adventure'}]",
     "[{'id':1562,'name':'ship'},{'id':849,'name':'love story'},{'id':9748,'name':'ocean'}]",
     "[{'name':'Leonardo DiCaprio'},{'name':'Kate Winslet'},{'name':'Billy Zane'}]",
     "[{'name':'James Cameron','job':'Director'}]",
     "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
     1997, 7.9, 24000, 194),

    ("Jurassic Park",
     "[{'id':12,'name':'Adventure'},{'id':878,'name':'Science Fiction'},{'id':53,'name':'Thriller'}]",
     "[{'id':1562,'name':'dinosaur'},{'id':849,'name':'island'},{'id':9748,'name':'genetics'}]",
     "[{'name':'Sam Neill'},{'name':'Laura Dern'},{'name':'Jeff Goldblum'}]",
     "[{'name':'Steven Spielberg','job':'Director'}]",
     "A pragmatic paleontologist visiting an almost-completed amusement park is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.",
     1993, 8.2, 16000, 127),

    ("Star Wars: A New Hope",
     "[{'id':28,'name':'Action'},{'id':12,'name':'Adventure'},{'id':878,'name':'Science Fiction'}]",
     "[{'id':1562,'name':'space'},{'id':849,'name':'force'},{'id':9748,'name':'rebellion'}]",
     "[{'name':'Mark Hamill'},{'name':'Harrison Ford'},{'name':'Carrie Fisher'}]",
     "[{'name':'George Lucas','job':'Director'}]",
     "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station.",
     1977, 8.6, 18000, 121),

    ("The Lord of the Rings: The Fellowship of the Ring",
     "[{'id':12,'name':'Adventure'},{'id':14,'name':'Fantasy'},{'id':28,'name':'Action'}]",
     "[{'id':1562,'name':'ring'},{'id':849,'name':'quest'},{'id':9748,'name':'middle earth'}]",
     "[{'name':'Elijah Wood'},{'name':'Ian McKellen'},{'name':'Viggo Mortensen'}]",
     "[{'name':'Peter Jackson','job':'Director'}]",
     "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
     2001, 8.8, 20000, 178),

    ("Harry Potter and the Sorcerer's Stone",
     "[{'id':12,'name':'Adventure'},{'id':14,'name':'Fantasy'},{'id':10751,'name':'Family'}]",
     "[{'id':1562,'name':'magic'},{'id':849,'name':'wizard'},{'id':9748,'name':'school'}]",
     "[{'name':'Daniel Radcliffe'},{'name':'Emma Watson'},{'name':'Rupert Grint'}]",
     "[{'name':'Chris Columbus','job':'Director'}]",
     "An orphaned boy enrolls in a school of wizardry, where he learns the truth about himself, his family and the terrible evil that haunts the magical world.",
     2001, 7.9, 20000, 152),

    ("Spider-Man",
     "[{'id':28,'name':'Action'},{'id':12,'name':'Adventure'},{'id':878,'name':'Science Fiction'}]",
     "[{'id':1562,'name':'superhero'},{'id':849,'name':'spider'},{'id':9748,'name':'new york'}]",
     "[{'name':'Tobey Maguire'},{'name':'Kirsten Dunst'},{'name':'Willem Dafoe'}]",
     "[{'name':'Sam Raimi','job':'Director'}]",
     "When bitten by a genetically modified spider, a nerdy, shy, and awkward high school student gains spider-like abilities that he eventually must use to fight evil as a superhero.",
     2002, 7.4, 16000, 121),

    ("Black Panther",
     "[{'id':28,'name':'Action'},{'id':12,'name':'Adventure'},{'id':878,'name':'Science Fiction'}]",
     "[{'id':1562,'name':'africa'},{'id':849,'name':'king'},{'id':9748,'name':'marvel'}]",
     "[{'name':'Chadwick Boseman'},{'name':'Michael B. Jordan'},{'name':'Lupita Nyong'}]",
     "[{'name':'Ryan Coogler','job':'Director'}]",
     "T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country's past.",
     2018, 7.3, 22000, 134),

    ("Get Out",
     "[{'id':27,'name':'Horror'},{'id':9648,'name':'Mystery'},{'id':53,'name':'Thriller'}]",
     "[{'id':1562,'name':'racism'},{'id':849,'name':'hypnosis'},{'id':9748,'name':'paranoia'}]",
     "[{'name':'Daniel Kaluuya'},{'name':'Allison Williams'},{'name':'Bradley Whitford'}]",
     "[{'name':'Jordan Peele','job':'Director'}]",
     "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.",
     2017, 7.7, 17000, 104),

    ("Parasite",
     "[{'id':35,'name':'Comedy'},{'id':53,'name':'Thriller'},{'id':18,'name':'Drama'}]",
     "[{'id':1562,'name':'class'},{'id':849,'name':'family'},{'id':9748,'name':'deception'}]",
     "[{'name':'Song Kang-ho'},{'name':'Lee Sun-kyun'},{'name':'Cho Yeo-jeong'}]",
     "[{'name':'Bong Joon-ho','job':'Director'}]",
     "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
     2019, 8.5, 15000, 132),

    ("Joker",
     "[{'id':80,'name':'Crime'},{'id':18,'name':'Drama'},{'id':53,'name':'Thriller'}]",
     "[{'id':1562,'name':'clown'},{'id':849,'name':'mental illness'},{'id':9748,'name':'gotham'}]",
     "[{'name':'Joaquin Phoenix'},{'name':'Robert De Niro'},{'name':'Zazie Beetz'}]",
     "[{'name':'Todd Phillips','job':'Director'}]",
     "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime.",
     2019, 8.4, 24000, 122),

    ("1917",
     "[{'id':10752,'name':'War'},{'id':18,'name':'Drama'},{'id':28,'name':'Action'}]",
     "[{'id':1562,'name':'world war i'},{'id':849,'name':'mission'},{'id':9748,'name':'trench'}]",
     "[{'name':'George MacKay'},{'name':'Dean-Charles Chapman'},{'name':'Mark Strong'}]",
     "[{'name':'Sam Mendes','job':'Director'}]",
     "April 6th, 1917. As a regiment assembles to wage war deep in enemy territory, two soldiers are assigned to race against time and deliver a message that will stop 1,600 men from walking straight into a deadly trap.",
     2019, 8.3, 14000, 119),

    ("The Grand Budapest Hotel",
     "[{'id':35,'name':'Comedy'},{'id':12,'name':'Adventure'},{'id':80,'name':'Crime'}]",
     "[{'id':1562,'name':'hotel'},{'id':849,'name':'europe'},{'id':9748,'name':'mystery'}]",
     "[{'name':'Ralph Fiennes'},{'name':'Tony Revolori'},{'name':'Saoirse Ronan'}]",
     "[{'name':'Wes Anderson','job':'Director'}]",
     "A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy in the hotel's glorious years under an exceptional concierge.",
     2014, 8.1, 17000, 99),
]


def generate_sample_dataset() -> pd.DataFrame:
    """Build a TMDB-shaped DataFrame from the embedded MOVIES list."""
    np.random.seed(42)

    rows = []
    for i, (title, genres, keywords, cast, crew, overview, year, rating, votes, runtime) in enumerate(MOVIES):
        rows.append({
            "movie_id":    i + 1,
            "title":       title,
            "genres":      genres,
            "keywords":    keywords,
            "cast":        cast,
            "crew":        crew,
            "overview":    overview,
            "release_date": f"{year}-06-15",
            "vote_average": rating,
            "vote_count":   votes,
            "runtime":      runtime,
            "popularity":   round(np.random.uniform(30, 250), 2),
        })

    return pd.DataFrame(rows)
